import { useState, useCallback } from 'react'
import { Sparkles, Copy, Check, ChevronDown } from 'lucide-react'
import { getExecutiveSummary } from '@/lib/api'
import { toast } from '@/hooks/use-toast'

interface ExecutiveSummaryProps {
  query: string
  insights: string[]
  chartsData: Record<string, unknown>[]
}

export default function ExecutiveSummary({ query, insights, chartsData }: ExecutiveSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [open, setOpen] = useState(false)

  const generate = useCallback(async () => {
    if (summary) { setOpen(o => !o); return }
    setOpen(true)
    setLoading(true)
    try {
      const text = await getExecutiveSummary(query, insights, chartsData)
      setSummary(text)
    } catch {
      setSummary('Could not generate summary. Please try again.')
    } finally {
      setLoading(false)
    }
  }, [summary, query, insights, chartsData])

  const handleCopy = () => {
    if (!summary) return
    navigator.clipboard.writeText(summary)
    setCopied(true)
    toast({ title: 'Copied', description: 'Executive summary copied to clipboard.' })
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="rounded-xl overflow-hidden border" style={{ borderColor: 'var(--border-default)', background: 'var(--bg-raised)' }}>
      <button
        onClick={generate}
        className="w-full flex items-center gap-2.5 px-4 py-3 text-left transition-colors hover:bg-[var(--bg-overlay)]"
      >
        <div className="w-1 h-5 rounded-full flex-shrink-0" style={{ background: 'var(--accent-base)' }} />
        <span className="text-xs font-mono uppercase tracking-widest font-semibold flex-1" style={{ color: 'var(--text-secondary)' }}>
          Executive Summary
        </span>
        {!loading && (
          <ChevronDown
            className="w-3.5 h-3.5 transition-transform"
            style={{ color: 'var(--text-tertiary)', transform: open ? 'rotate(180deg)' : 'none' }}
          />
        )}
        {loading && (
          <div className="w-3.5 h-3.5 border rounded-full animate-spin border-t-transparent"
            style={{ borderColor: 'var(--accent-base)', borderTopColor: 'transparent' }} />
        )}
      </button>

      {open && (
        <div className="px-4 pb-4 border-t" style={{ borderColor: 'var(--border-faint)' }}>
          {loading ? (
            <div className="flex items-center gap-2 py-4">
              <Sparkles className="w-4 h-4 animate-pulse" style={{ color: 'var(--accent-base)' }} />
              <span className="text-xs font-mono" style={{ color: 'var(--text-tertiary)' }}>Generating executive brief...</span>
            </div>
          ) : summary ? (
            <>
              <p className="text-sm leading-[1.8] mt-3" style={{ color: 'var(--text-secondary)', fontFamily: 'var(--font-base)' }}>
                {summary}
              </p>
              <div className="flex items-center gap-3 mt-3">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 text-xs px-2.5 py-1.5 rounded-lg border transition-colors hover:bg-[var(--bg-overlay)]"
                  style={{ borderColor: 'var(--border-default)', color: 'var(--text-tertiary)' }}
                >
                  {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied!' : 'Copy as Text'}
                </button>
                <span className="text-xs" style={{ color: 'var(--text-disabled)', fontFamily: 'var(--font-base)' }}>
                  Generated by AI · Verify before sharing
                </span>
              </div>
            </>
          ) : null}
        </div>
      )}
    </div>
  )
}
